# Generated by Django 4.1.2 on 2022-12-19 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_proyect_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(default='defauld value', max_length=40)),
                ('apellido', models.CharField(default='default value', max_length=40)),
                ('cargo', models.CharField(default='default value', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Silabo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente', models.CharField(max_length=20)),
                ('silabo', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='OdersTablas',
        ),
        migrations.DeleteModel(
            name='Uasers',
        ),
        migrations.AddField(
            model_name='task',
            name='OdersTablas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.project'),
        ),
    ]
