# Generated by Django 4.1.3 on 2022-11-15 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_proyect_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='OdersTablas',
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('OdersTablas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.uasers')),
            ],
        ),
    ]
