# Generated by Django 4.1.2 on 2022-12-19 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_docentes_silabo_task_remove_project_oderstablas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silabo',
            name='docente',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='myapp.docentes'),
        ),
    ]
