# Generated by Django 4.1.3 on 2022-11-15 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_project_oderstablas_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='OdersTablas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.project'),
        ),
    ]
