# Generated by Django 4.1.2 on 2022-12-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_silabo_docente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('uploadfile', models.FileField(upload_to='uploaded Files')),
                ('dataTimeOfUpload', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
