# Generated by Django 4.1.2 on 2022-12-21 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='OdersTablas',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
