# Generated by Django 4.1.2 on 2022-12-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_task_oderstablas_delete_project_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='cargaAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TI_DO', models.CharField(default='defauld value', max_length=10)),
                ('DOCENTE', models.CharField(default='defauld value', max_length=80)),
                ('IDENT', models.PositiveIntegerField()),
                ('PR_DE', models.CharField(default='defauld value', max_length=10)),
                ('CARRERA', models.CharField(default='defauld value', max_length=50)),
                ('CURSO', models.CharField(default='defauld value', max_length=80)),
                ('CRED', models.PositiveIntegerField()),
                ('TIPO', models.CharField(default='defauld value', max_length=2)),
                ('GPO', models.CharField(default='defauld value', max_length=2)),
                ('HT', models.PositiveIntegerField()),
                ('HP', models.PositiveIntegerField()),
                ('DIA', models.CharField(default='defauld value', max_length=10)),
                ('HR_INICIO', models.PositiveIntegerField()),
                ('HR_FIN', models.PositiveIntegerField()),
                ('AULA', models.CharField(default='defauld value', max_length=10)),
                ('LIMITE', models.PositiveIntegerField()),
                ('MATRICULADOS', models.PositiveIntegerField()),
            ],
        ),
    ]
