# Generated by Django 4.1.2 on 2022-12-25 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_cargaacademica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='uploadfile',
            field=models.FileField(upload_to='myapp/files/'),
        ),
    ]
