# Generated by Django 4.1.2 on 2022-12-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_document_uploadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargaacademica',
            name='id',
            field=models.PositiveIntegerField(default='default value', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='docentes',
            name='id',
            field=models.PositiveIntegerField(default='default value', primary_key=True, serialize=False),
        ),
    ]
