# Generated by Django 4.1.2 on 2022-12-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_cargaacademica_id_docente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docentes',
            name='id',
            field=models.PositiveIntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
