# Generated by Django 4.1.2 on 2022-12-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_docentes_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='docentes',
            name='id_docente',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='docentes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
