# Generated by Django 4.1.2 on 2022-12-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_docentes_id_docente_alter_docentes_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docentes',
            name='id_docente',
            field=models.PositiveIntegerField(),
        ),
    ]
