# Generated by Django 4.1.2 on 2023-01-14 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_document_uploadfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avance_Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tema', models.CharField(max_length=400)),
                ('FechaAvance', models.DateTimeField(auto_now=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.docentes')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia_Out',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HoraSalida', models.TimeField()),
                ('FechaOut', models.DateField(unique=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.docentes')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia_In',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HoraEntrada', models.TimeField()),
                ('FechaIn', models.DateField(unique=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.docentes')),
            ],
        ),
    ]
