# Generated by Django 4.1.2 on 2023-01-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_avance_docente_asistencia_out_asistencia_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='silabo',
            name='curso',
            field=models.CharField(default='default value', max_length=100),
        ),
    ]
