# Generated by Django 4.1.2 on 2023-01-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_silabo_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='silabo',
            name='id_Docente',
            field=models.CharField(default='default value', max_length=5),
        ),
    ]
