# Generated by Django 4.1.2 on 2023-01-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_silabo_id_docente'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia_in',
            name='Asistencia_curso',
            field=models.CharField(default='default value', max_length=100),
        ),
        migrations.AddField(
            model_name='asistencia_in',
            name='id_Docente',
            field=models.CharField(default='default value', max_length=5),
        ),
        migrations.AddField(
            model_name='avance_docente',
            name='Avance_curso',
            field=models.CharField(default='default value', max_length=100),
        ),
        migrations.AddField(
            model_name='avance_docente',
            name='id_Docente_Avance',
            field=models.CharField(default='default value', max_length=5),
        ),
        migrations.DeleteModel(
            name='Asistencia_Out',
        ),
    ]
