# Generated by Django 4.1.2 on 2023-01-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_asistencia_in_asistencia_curso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia_in',
            name='FechaIn',
            field=models.DateField(),
        ),
    ]
