# Generated by Django 4.1.2 on 2023-01-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_asistencia_in_fechain'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia_in',
            name='codigo_curso',
            field=models.CharField(default='default value', max_length=10),
        ),
        migrations.AddField(
            model_name='avance_docente',
            name='codigo_curso',
            field=models.CharField(default='default value', max_length=10),
        ),
    ]
