# Generated by Django 4.1.2 on 2023-01-31 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alumno_lista_alumnos_registro_alumnos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Silabo_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(max_length=10)),
                ('codigo_curso', models.CharField(default='default value', max_length=10)),
                ('id_Docente_Avance', models.CharField(default='default value', max_length=5)),
                ('Nombre_curso', models.CharField(default='default value', max_length=50)),
                ('Contenido', models.CharField(max_length=300)),
                ('Actividades', models.CharField(max_length=300)),
                ('Tiempo', models.CharField(max_length=2)),
                ('FechaInicio', models.DateField()),
                ('FechaFinal', models.DateField()),
                ('Unidad', models.CharField(max_length=1)),
            ],
        ),
    ]
