# Generated by Django 4.1.2 on 2023-02-01 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_silabo_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='silabo_content',
            name='semestre',
        ),
        migrations.AlterField(
            model_name='silabo_content',
            name='Tiempo',
            field=models.PositiveIntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='silabo_content',
            name='Unidad',
            field=models.CharField(max_length=15),
        ),
    ]
