# Generated by Django 4.1.2 on 2023-02-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_remove_silabo_content_semestre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silabo_content',
            name='Tiempo',
            field=models.PositiveIntegerField(),
        ),
    ]
