# Generated by Django 4.1.2 on 2023-02-02 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_silabo_content_tiempo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro_alumnos',
            name='Apellidos',
        ),
        migrations.AlterField(
            model_name='registro_alumnos',
            name='Nombres',
            field=models.CharField(default='defauld value', max_length=120),
        ),
    ]
